version: "2"

services:
  console:
    image: whalesil/ishmael:development
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /code
    volumes:
        - ../temp:/repos
        - .:/code
        - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    env_file:
        - dev.env
